version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cv-voting-db
    environment:
      - POSTGRES_DB=cvvoting
      - POSTGRES_USER=cvvoting
      - POSTGRES_PASSWORD=cvvoting
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cv-voting-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cv-voting-backend
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - REDIRECT_URI=${PROD_DOMAIN}/auth/callback
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://cvvoting:cvvoting@db:5432/cvvoting
    volumes:
      - ./backend:/app
    networks:
      - cv-voting-network
    restart: unless-stopped
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cv-voting-frontend
    environment:
      - VITE_API_BASE_URL=${PROD_DOMAIN}
    volumes:
      - frontend_build:/usr/share/nginx/html
    networks:
      - cv-voting-network
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: cv-voting-nginx
    volumes:
      - frontend_build:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend
    networks:
      - cv-voting-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  cv-voting-network:
    driver: bridge

volumes:
  backend_data:
  postgres_data:
  frontend_build: 